export const editorTheme = {
  ltr: "ltr",
  rtl: "rtl",
  paragraph: "editor-paragraph mb-4 relative",
  quote: "editor-quote border-l-4 border-gray-300 pl-4 italic",
  heading: {
    h1: "editor-heading-h1 text-3xl font-bold mb-4",
    h2: "editor-heading-h2 text-2xl font-bold mb-3",
    h3: "editor-heading-h3 text-xl font-bold mb-2",
    h4: "editor-heading-h4 text-lg font-bold mb-2",
    h5: "editor-heading-h5 text-base font-bold mb-1",
    h6: "editor-heading-h6 text-sm font-bold mb-1",
  },
  list: {
    nested: {
      listitem: "editor-nested-listitem ml-4",
    },
    ol: "editor-list-ol list-decimal list-inside mb-4",
    ul: "editor-list-ul list-disc list-inside mb-4",
    listitem: "editor-listitem mb-1",
  },
  image: "editor-image",
  link: "editor-link text-blue-600 underline cursor-pointer",
  text: {
    bold: "editor-text-bold font-bold",
    italic: "editor-text-italic italic",
    overflowed: "editor-text-overflowed",
    hashtag: "editor-text-hashtag text-blue-600",
    underline: "editor-text-underline underline",
    strikethrough: "editor-text-strikethrough line-through",
    underlineStrikethrough: "editor-text-underlineStrikethrough underline line-through",
    code: "editor-text-code bg-gray-100 p-1 rounded font-mono text-sm",
  },
  code: "editor-code bg-gray-100 p-4 rounded font-mono text-sm mb-4 block overflow-x-auto",
  codeHighlight: {
    atrule: "editor-tokenAttr text-[#007ba5]",
    attr: "editor-tokenAttr text-[#007ba5]",
    boolean: "editor-tokenProperty text-[#905]",
    builtin: "editor-tokenSelector text-[#690]",
    cdata: "editor-tokenComment text-[#708090]",
    char: "editor-tokenSelector text-[#690]",
    class: "editor-tokenFunction text-[#dd4a68]",
    "class-name": "editor-tokenFunction text-[#dd4a68]",
    comment: "editor-tokenComment text-[#708090]",
    constant: "editor-tokenProperty text-[#905]",
    deleted: "editor-tokenProperty text-[#905]",
    doctype: "editor-tokenComment text-[#708090]",
    entity: "editor-tokenOperator text-[#9a6e3a]",
    function: "editor-tokenFunction text-[#dd4a68]",
    important: "editor-tokenVariable text-[#e90]",
    inserted: "editor-tokenSelector text-[#690]",
    keyword: "editor-tokenAttr text-[#007ba5]",
    namespace: "editor-tokenVariable text-[#e90]",
    number: "editor-tokenProperty text-[#905]",
    operator: "editor-tokenOperator text-[#9a6e3a]",
    prolog: "editor-tokenComment text-[#708090]",
    property: "editor-tokenProperty text-[#905]",
    punctuation: "editor-tokenPunctuation text-[#999]",
    regex: "editor-tokenVariable text-[#e90]",
    selector: "editor-tokenSelector text-[#690]",
    string: "editor-tokenSelector text-[#690]",
    symbol: "editor-tokenProperty text-[#905]",
    tag: "editor-tokenProperty text-[#905]",
    url: "editor-tokenOperator text-[#9a6e3a]",
    variable: "editor-tokenVariable text-[#e90]",
  },
};
