/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as AdminMediaRouteImport } from './routes/admin/media'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminAuthorsRouteImport } from './routes/admin/authors'
import { Route as PublicSearchRouteImport } from './routes/_public/search'
import { Route as AdminArticlesIndexRouteImport } from './routes/admin/articles/index'
import { Route as AdminArticlesNewRouteImport } from './routes/admin/articles/new'
import { Route as AdminArticlesIdRouteImport } from './routes/admin/articles/$id'
import { Route as PublicCategorySlugRouteImport } from './routes/_public/category/$slug'
import { Route as PublicArticleSlugRouteImport } from './routes/_public/article/$slug'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuthorsRoute = AdminAuthorsRouteImport.update({
  id: '/authors',
  path: '/authors',
  getParentRoute: () => AdminRoute,
} as any)
const PublicSearchRoute = PublicSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => PublicRoute,
} as any)
const AdminArticlesIndexRoute = AdminArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArticlesNewRoute = AdminArticlesNewRouteImport.update({
  id: '/articles/new',
  path: '/articles/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArticlesIdRoute = AdminArticlesIdRouteImport.update({
  id: '/articles/$id',
  path: '/articles/$id',
  getParentRoute: () => AdminRoute,
} as any)
const PublicCategorySlugRoute = PublicCategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const PublicArticleSlugRoute = PublicArticleSlugRouteImport.update({
  id: '/article/$slug',
  path: '/article/$slug',
  getParentRoute: () => PublicRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/search': typeof PublicSearchRoute
  '/admin/authors': typeof AdminAuthorsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/': typeof AdminIndexRoute
  '/article/$slug': typeof PublicArticleSlugRoute
  '/category/$slug': typeof PublicCategorySlugRoute
  '/admin/articles/$id': typeof AdminArticlesIdRoute
  '/admin/articles/new': typeof AdminArticlesNewRoute
  '/admin/articles/': typeof AdminArticlesIndexRoute
}
export interface FileRoutesByTo {
  '/search': typeof PublicSearchRoute
  '/admin/authors': typeof AdminAuthorsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/media': typeof AdminMediaRoute
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminIndexRoute
  '/article/$slug': typeof PublicArticleSlugRoute
  '/category/$slug': typeof PublicCategorySlugRoute
  '/admin/articles/$id': typeof AdminArticlesIdRoute
  '/admin/articles/new': typeof AdminArticlesNewRoute
  '/admin/articles': typeof AdminArticlesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/_public/search': typeof PublicSearchRoute
  '/admin/authors': typeof AdminAuthorsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/media': typeof AdminMediaRoute
  '/_public/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_public/article/$slug': typeof PublicArticleSlugRoute
  '/_public/category/$slug': typeof PublicCategorySlugRoute
  '/admin/articles/$id': typeof AdminArticlesIdRoute
  '/admin/articles/new': typeof AdminArticlesNewRoute
  '/admin/articles/': typeof AdminArticlesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/search'
    | '/admin/authors'
    | '/admin/categories'
    | '/admin/media'
    | '/admin/'
    | '/article/$slug'
    | '/category/$slug'
    | '/admin/articles/$id'
    | '/admin/articles/new'
    | '/admin/articles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/search'
    | '/admin/authors'
    | '/admin/categories'
    | '/admin/media'
    | '/'
    | '/admin'
    | '/article/$slug'
    | '/category/$slug'
    | '/admin/articles/$id'
    | '/admin/articles/new'
    | '/admin/articles'
  id:
    | '__root__'
    | '/_public'
    | '/admin'
    | '/_public/search'
    | '/admin/authors'
    | '/admin/categories'
    | '/admin/media'
    | '/_public/'
    | '/admin/'
    | '/_public/article/$slug'
    | '/_public/category/$slug'
    | '/admin/articles/$id'
    | '/admin/articles/new'
    | '/admin/articles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/authors': {
      id: '/admin/authors'
      path: '/authors'
      fullPath: '/admin/authors'
      preLoaderRoute: typeof AdminAuthorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/search': {
      id: '/_public/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof PublicSearchRouteImport
      parentRoute: typeof PublicRoute
    }
    '/admin/articles/': {
      id: '/admin/articles/'
      path: '/articles'
      fullPath: '/admin/articles/'
      preLoaderRoute: typeof AdminArticlesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/articles/new': {
      id: '/admin/articles/new'
      path: '/articles/new'
      fullPath: '/admin/articles/new'
      preLoaderRoute: typeof AdminArticlesNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/articles/$id': {
      id: '/admin/articles/$id'
      path: '/articles/$id'
      fullPath: '/admin/articles/$id'
      preLoaderRoute: typeof AdminArticlesIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/category/$slug': {
      id: '/_public/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof PublicCategorySlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/article/$slug': {
      id: '/_public/article/$slug'
      path: '/article/$slug'
      fullPath: '/article/$slug'
      preLoaderRoute: typeof PublicArticleSlugRouteImport
      parentRoute: typeof PublicRoute
    }
  }
}

interface PublicRouteChildren {
  PublicSearchRoute: typeof PublicSearchRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicArticleSlugRoute: typeof PublicArticleSlugRoute
  PublicCategorySlugRoute: typeof PublicCategorySlugRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicSearchRoute: PublicSearchRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicArticleSlugRoute: PublicArticleSlugRoute,
  PublicCategorySlugRoute: PublicCategorySlugRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface AdminRouteChildren {
  AdminAuthorsRoute: typeof AdminAuthorsRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminArticlesIdRoute: typeof AdminArticlesIdRoute
  AdminArticlesNewRoute: typeof AdminArticlesNewRoute
  AdminArticlesIndexRoute: typeof AdminArticlesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuthorsRoute: AdminAuthorsRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminArticlesIdRoute: AdminArticlesIdRoute,
  AdminArticlesNewRoute: AdminArticlesNewRoute,
  AdminArticlesIndexRoute: AdminArticlesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
